### POST save
POST http://localhost:8080/
Host: localhost:8080
Content-Type: text/plain

https://ya.com


### POST apiSave
POST http://localhost:8080/api/shorten
Host: localhost:8080
Content-Type: application/json

{
  "url": "https://practicum.yandex.com/",
  "alias": "123df23"
}

### Get
# @no-redirect
GET http://localhost:8080/123df23


### POST apiSave
POST http://localhost:8080/api/shorten
Host: localhost:8080
Content-Type: application/json
Cookie: UserID=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5ODl9.VEGdChrqZwqxrLpDz55LEXEX_lCBFKpTNzMshm6EYjk

{
  "url": "https://practicum.yandex.com/",
  "alias": "123df23"
}

### GET request with cookie passed through headers
# @no-redirect
GET http://localhost:8080/api/user/urls
Cookie: UserID=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5ODl9.VEGdChrqZwqxrLpDz55LEXEX_lCBFKpTNzMshm6EYjk