### POST
POST http://localhost:8080
Host: localhost:8080
Content-Type: text/plain

https://google.ru


### GET ping
GET http://localhost:8080/ping

### POST save
POST http://localhost:8080/
Host: localhost:8080
Content-Type: text/plain

https://google.com


### POST request without cookies
< {%
    const rand = $random.alphabetic(5).toLowerCase()
    request.variables.set("rand", rand)
%}

POST http://localhost:8080/api/shorten
Host: localhost:8080
Content-Type: application/json

{
  "url": "http:\/\/{{rand}}.com/",
  "alias": ""
}

### Get
# @no-redirect
GET http://localhost:8080/0CF75HmO


### POST request with cookie
< {%
    const srv = $random.alphabetic(8).toLowerCase()
    const alias = $random.alphanumeric(5).toLowerCase()
    request.variables.set("srv", srv)
    request.variables.set("alias", alias)
%}

POST http://localhost:8080/api/shorten
Host: localhost:8080
Content-Type: application/json
Cookie: UserID=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5MjR9.3-u9JqljBCsqfT_yrPfIpwwvKtoryZYuLB_UouDB5TM

{
  "url": "http:\/\/{{srv}}.com/",
  "alias": "{{alias}}"
}

### GET all
# @no-redirect
GET http://localhost:8080/api/user/urls
Cookie: UserID=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5MjR9.3-u9JqljBCsqfT_yrPfIpwwvKtoryZYuLB_UouDB5TM

### DELETE
DELETE http://localhost:8080/api/user/urls
Cookie: UserID=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5MjR9.3-u9JqljBCsqfT_yrPfIpwwvKtoryZYuLB_UouDB5TM

["6i2NVBw5"]

### GET stats
GET http://localhost:8080/api/internal/stats
X-Real-IP: 10.0.1.242