// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: proto/shortener.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Links_Get_FullMethodName          = "/proto.Links/Get"
	Links_Save_FullMethodName         = "/proto.Links/Save"
	Links_GetAll_FullMethodName       = "/proto.Links/GetAll"
	Links_Del_FullMethodName          = "/proto.Links/Del"
	Links_Healthcheck_FullMethodName  = "/proto.Links/Healthcheck"
	Links_BatchShorten_FullMethodName = "/proto.Links/BatchShorten"
)

// LinksClient is the client API for Links service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC service definition for managing links.
type LinksClient interface {
	// RPC to get the long link from a shortened link.
	Get(ctx context.Context, in *ShortenLink, opts ...grpc.CallOption) (*ShortenLinkResponse, error)
	// RPC to save a long link and get its shortened version.
	Save(ctx context.Context, in *LongLink, opts ...grpc.CallOption) (*LongLinkResponse, error)
	// RPC to get all shortened links for a user.
	GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListShortenLinks, error)
	// RPC to delete specified shortened links.
	Del(ctx context.Context, in *ListShortenLinksToDelete, opts ...grpc.CallOption) (*Empty, error)
	// RPC to check the health of the service.
	Healthcheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	// RPC to process multiple URLs in a batch and return their shortened versions.
	BatchShorten(ctx context.Context, in *BatchShortenRequest, opts ...grpc.CallOption) (*BatchShortenResponse, error)
}

type linksClient struct {
	cc grpc.ClientConnInterface
}

func NewLinksClient(cc grpc.ClientConnInterface) LinksClient {
	return &linksClient{cc}
}

func (c *linksClient) Get(ctx context.Context, in *ShortenLink, opts ...grpc.CallOption) (*ShortenLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortenLinkResponse)
	err := c.cc.Invoke(ctx, Links_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linksClient) Save(ctx context.Context, in *LongLink, opts ...grpc.CallOption) (*LongLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LongLinkResponse)
	err := c.cc.Invoke(ctx, Links_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linksClient) GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListShortenLinks, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShortenLinks)
	err := c.cc.Invoke(ctx, Links_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linksClient) Del(ctx context.Context, in *ListShortenLinksToDelete, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Links_Del_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linksClient) Healthcheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, Links_Healthcheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linksClient) BatchShorten(ctx context.Context, in *BatchShortenRequest, opts ...grpc.CallOption) (*BatchShortenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchShortenResponse)
	err := c.cc.Invoke(ctx, Links_BatchShorten_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinksServer is the server API for Links service.
// All implementations must embed UnimplementedLinksServer
// for forward compatibility
//
// gRPC service definition for managing links.
type LinksServer interface {
	// RPC to get the long link from a shortened link.
	Get(context.Context, *ShortenLink) (*ShortenLinkResponse, error)
	// RPC to save a long link and get its shortened version.
	Save(context.Context, *LongLink) (*LongLinkResponse, error)
	// RPC to get all shortened links for a user.
	GetAll(context.Context, *Empty) (*ListShortenLinks, error)
	// RPC to delete specified shortened links.
	Del(context.Context, *ListShortenLinksToDelete) (*Empty, error)
	// RPC to check the health of the service.
	Healthcheck(context.Context, *Empty) (*HealthcheckResponse, error)
	// RPC to process multiple URLs in a batch and return their shortened versions.
	BatchShorten(context.Context, *BatchShortenRequest) (*BatchShortenResponse, error)
	mustEmbedUnimplementedLinksServer()
}

// UnimplementedLinksServer must be embedded to have forward compatible implementations.
type UnimplementedLinksServer struct {
}

func (UnimplementedLinksServer) Get(context.Context, *ShortenLink) (*ShortenLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedLinksServer) Save(context.Context, *LongLink) (*LongLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedLinksServer) GetAll(context.Context, *Empty) (*ListShortenLinks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedLinksServer) Del(context.Context, *ListShortenLinksToDelete) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedLinksServer) Healthcheck(context.Context, *Empty) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthcheck not implemented")
}
func (UnimplementedLinksServer) BatchShorten(context.Context, *BatchShortenRequest) (*BatchShortenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchShorten not implemented")
}
func (UnimplementedLinksServer) mustEmbedUnimplementedLinksServer() {}

// UnsafeLinksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinksServer will
// result in compilation errors.
type UnsafeLinksServer interface {
	mustEmbedUnimplementedLinksServer()
}

func RegisterLinksServer(s grpc.ServiceRegistrar, srv LinksServer) {
	s.RegisterService(&Links_ServiceDesc, srv)
}

func _Links_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenLink)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Links_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).Get(ctx, req.(*ShortenLink))
	}
	return interceptor(ctx, in, info, handler)
}

func _Links_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LongLink)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Links_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).Save(ctx, req.(*LongLink))
	}
	return interceptor(ctx, in, info, handler)
}

func _Links_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Links_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).GetAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Links_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShortenLinksToDelete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Links_Del_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).Del(ctx, req.(*ListShortenLinksToDelete))
	}
	return interceptor(ctx, in, info, handler)
}

func _Links_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Links_Healthcheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).Healthcheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Links_BatchShorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchShortenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).BatchShorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Links_BatchShorten_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).BatchShorten(ctx, req.(*BatchShortenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Links_ServiceDesc is the grpc.ServiceDesc for Links service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Links_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Links",
	HandlerType: (*LinksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Links_Get_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _Links_Save_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _Links_GetAll_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _Links_Del_Handler,
		},
		{
			MethodName: "Healthcheck",
			Handler:    _Links_Healthcheck_Handler,
		},
		{
			MethodName: "BatchShorten",
			Handler:    _Links_BatchShorten_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shortener.proto",
}
